# Generated by Django 5.2.11 on 2026-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='count',
        ),
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=1),
        ),
    ]
